[package]
name = "surreal_devl"
version = "0.1.0"
edition = "2021"

[package.metadata]
# Will log the query command at runtime
surreal_enable_log = false
# Log the generated code at build time
surreal_enable_compile_log = false
surreal_enable_snake_case = true
surreal_namespace = "surrealql-derive"
surreal_info_log_macro = "println"
surreal_warn_log_macro = "println"

[dependencies]
surrealdb = "1.0.0"
cargo_metadata = "0.18.1"
