[package]
name = "surreal_devl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata]
surreal_enable_log = false
surreal_enable_snake_case = false
surreal_namespace = "surrealql-derive"
surreal_info_log_macro = "println"
surreal_warn_log_macro = "println"

[dependencies]
surrealdb = "1.0.0"
cargo_metadata = "0.18.1"
